url: "https://fen.cx"
title: "fen's website!"
description: "the website of a nerdy furry queer orange internet cat"
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      style: "main"
      script: "main"
